spdk/spdk-ci

.github/workflows/spdk-common-tests.yml

Curl needs an "-L" argument to be able to handle redirects.
Additionally update Gerrit's URL by removing "/gerrit" block, as it's no longer needed due to recent configuration changes.

Workflow curl fix and minor Gerrit URL update

---

.github/actions/checkout_gerrit/action.yml
.github/workflows/gerrit-webhook-handler.yml
.github/workflows/spdk-common-tests.yml

This series first starts off by adding composite action `checkout_gerrit` that checks out SPDK from GitHub and fetches specific patch set from Gerrit.
Later added way to manually run both workflows for debugging purposes. Meanwhile the gerrit-webhook can now be triggered on new PRs.
Note that this can result in some steps/jobs being skipped, for example no reporting back to Gerrit is needed (nor it is set up for 'testing').

Check out SPDK and run on PR/manually

---

.github/workflows/per_patch.yml

Previously the value was hard-coded to some random succesfull build. Instead always select latest build.
This comes in handy when testing on GH forks, as then the build was never the same.
Obviously once multiple images will be at play, more complex logic will be needed. For example to select specific branch, maybe rather than date select by latest commit, etc. Otherwise we might run into irrelevant qcow2 builds ruining per-patch testing.

per-patch: select latest qcow2 build

---

.github/workflows/build_qcow2.yml

Change name to gerrit_ref and remove traces
of previous branch-oriented approach.

build_qcow: fix gerrit refspec variable names

---

.github/workflows/gerrit-webhook-handler.yml

Skip running complete SPDK tests for pull requests done for:
* selftest.yml workflow - because it's just a set of pre-commit linters not affecting SPDK tests themselves.
* build_qcow2.yml - because the per-patch build triggered by the PR is still using qcow2 image which doesn't contain the changes from the PR.

Skip SPDK tests on certain pull requests

---

.github/workflows/spdk-common-tests.yml
cijoe/workflows/autorun_in_qemu.yaml

Generate code coverage and run tests summary.
Script is run with "-s" flag which makes autorun_post NOT fail in case not all tests were run.

Run spdk/autorun_post on common tests artifacts

---

.github/workflows/spdk-common-tests.yml

... yet again! Recent builds triggered by Gerrit
webhook events show that SPDK source is checked-out using wrong respec.
This change fixes that.
For example:
[This change](https://review.spdk.io/c/spdk/spdk/+/25675/1#message-d7542753e7192a6eb24e8361aa6f6c03b56bc592) triggered https://github.com/spdk/spdk-ci/actions/runs/13716593637
but the build summary showed this as SPDK source being pulled for build:
```
[SPDK Repository] GitHub: master
Ref: d0bb35429 pkgdep: add xxd
```

Fix spdk-common-tests workflow_call

---

.github/workflows/spdk-common-tests.yml

Path replacement in input coverage files was moved to spdk/autorun_post.py itself.
See: https://review.spdk.io/c/spdk/spdk/+/25675
Tested at: https://github.com/karlatec/spdk-ci/actions/runs/13716702764

Remove "sed" for autorun_post.py input files

---

.github/workflows/build_qcow2.yml
.github/workflows/per_patch.yml

Artifact download takes between 1-3 minutes on every job in the per-patch matrix. Instead we can cache the image reducing, download to 20-30 seconds.
Currently only the one and only VM image is cached. It takes almost 3GB, while cache is limited to 10GB. While we could explore caching other artifacts shared on per-patch basis - like SPDK repo, but we need to be careful not to boot the VM image out of the cache.
Note: used hashFiles() instead of checking cache-hit output, because it was not set despite hitting the cache.

build_qcow: cache the VM image for faster spin up of every job

---

.github/workflows/build_qcow2.yml

Turns out that saving cache entry with the same key, failed just with a warning. As a result cache for the image remained, and even future rebuilds succeeding - did not over-write the cache. Jobs would pull in the cached entry refering to the wrong VM image.
I think the idea for cache entries here would be to match based on some pattern for the most recent entry like:
`vm-image-fedora-x86_64-spdk_sha-spdk-ci_sha-timestamp`
So that every cache is unique and can be pattern matched to desired item. While the ones that are unused would be forced out of cache.
We still have to rethink image generation.
Instead of that for now just delete prior entry matched by the key and save new one.
Yes, there is no official action to do that so instead gh tool is used on an ubuntu-latest runner.

build_qcow2: delete previous cached VM image

---

.github/actions/checkout_gerrit/action.yml
.github/workflows/gerrit-webhook-handler.yml
.github/workflows/summary.yml

Summary artifact will now be one stop shop for all SPDK
related artifacts, by including all job ouputs too.
While here, the pattern for upload just matched few
directories explicitly, missing files like 'completions_table.html'.
Instead just put everything into one dir pointed to by '-d',
which should include such dangling files or any future artifacts.

Combine job results into the summary

---

.github/workflows/summary.yml

Accounting for every expected test actually executing allows us to turn back voting on patches.
skipped_tests.txt in SPDK should now reflect what is not executing on SPDK-CI. Meanwhile any new added test will be immediately accounted for.

summary: enable voting on patch after aggregating the tests

---

.github/workflows/spdk-common-tests.yml
cijoe/scripts/qemu_guest_start_custom_nvme.py
cijoe/workflows/autorun_in_qemu.yaml

This PR addresses an intermittent issue where ``systemctl poweroff`` fails, leading to job failures. Examples:
- https://github.com/spdk/spdk-ci/actions/runs/14344360881/job/40211018925
- https://github.com/spdk/spdk-ci/actions/runs/13991159271/job/39358049352
The final commit is expected to resolve this issue.
The first two commits update ``cijoe`` to the latest release and adjust the guest-starting script accordingly.

Upgrade cijoe and fix intermittent guest shutdown error

---

.github/workflows/spdk-common-tests.yml

Graceful shutdowns (e.g., systemctl poweroff) fail intermittently, leading to errors. Since shutdown isn't required in the GitHub Runner environment, the workflow no longer calls the guest_shutdown step in the autorun_in_qemu job.
Note: In self-hosted environments, stray QEMU processes must be handled separately. The guest_shutdown step is retained for those cases, though it's unused here.

fix(autorun_in_qemu): skip guest shutdown to prevent errors

---

.github/workflows/gerrit-webhook-handler.yml

Use actual event names which are used in messages generated by Gerrit's Webhooks plugin to trigger repository_dispatch builds. Added items match the configuration currently enabled on Gerrit's side.
At the moment all events forwarded from Gerrit have their type replaced to "per-patch-event". We want to differentiate between the events, so this behavior will be disabled soon, along with removal of "per-patch-event" from repository_dispatch list.

Handle more events for repository_dispatch builds

---

.github/workflows/gerrit-false-positives-handler.yml
.github/workflows/gerrit-webhook-handler.yml

repository_dispatch payload is an object,
it needs to be converted to string before assignment.
Otherwise following error was ocurring:
```
The template is not valid. .github/workflows/gerrit-false-positives-handler.yml (Line: 16, Col: 19): A mapping was not expected
```
Besides that the "||" statements do not behave as one might expect. https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example
False positive job won't be able to do anything with empty client_payload, so throw it out.
Meanwhile per-patch was intended to test latest SPDK when client_payload is not passed. Until this is figured out just make that default behaviour and disable passing client_payload as input for manual runs.

gerrit: fix client_payload mapping

---

.github/workflows/gerrit-false-positives-handler.yml

The URL was recently changed to include run attempt, ex: https://github.com/spdk/spdk-ci/actions/runs/1234567/attempts/3
This made it impossible to rerun old builds with just the run id: https://github.com/spdk/spdk-ci/actions/runs/1234567
By simplifying the regex, both will be matched.

false_positive: be less restrictive searching for last failed build

---

.github/scripts/parse_false_positive_comment.sh
.github/workflows/gerrit-false-positives-handler.yml
.pre-commit-config.yaml

Move the entire code block to a separate script to not bother with how strings are extrapolated through .yaml->shell, pass all relevant pieces through environment.
Current implementation is buggy as it doesn't properly quote comment's contents, allowing it to actually execute code. Consider a valid comment posted on gerrit:
"I am going to `sudo rm -rf /` your entire github runner"
The `` is substituted into actual cmd while still being a valid format to simply quote code in gerrit's comments.

.github/workflows: Refactor false-positive parser

---

.github/scripts/parse_false_positive_comment.sh

Even though the actual json holds literal "\n\n" as part of the string this is expanded into actual newlines in the environment. Make sure the regex takes that into consideration.

.github/scripts: Fix regex against the .comment string

---

.github/workflows/gerrit-webhook-handler.yml

There's no automated tests or automated deployments for changes done in "infra" directory, so there's
no way to check if they'd affect SPDK workflows.
Thus, there's no point in running SPDK workflows
and taking runners time.

Do not run SPDK tests for infra changes

---

infra/docker-compose.yaml
infra/mergable_changes/Dockerfile
infra/mergable_changes/mergable_changes.py

Bring back "mergable changes" which was available in previous CI, under Intel umbrella. This script queries Gerrit for +2CR/+1 Verified changes, makes additional checks like:
- is there a merge conflict flag for the change
- is there a -1CR vote beside +2CR votes
- are any parents of the change (if it's a series) not mergable and presents the information organized in tables.
Text version with ASCII tables for now, but with
plans to bring back HTML version in nearby future.

infra: bring back mergable_changes service (text version)

---

.github/scripts/parse_false_positive_comment.sh
.github/workflows/gerrit-webhook-handler.yml

After running the patch_set_status job for a few days, there needed to be few fixes and additional comments to help narrow down the cause for skipping tests.
Especially important is the change for verified vote on completely new patch. Obviously such patch had no prior votes and while the step exited with failure, workflow was not canceled. So job proceeded as expected, just with supposedly failed step. Fixed that to fail gracefully in such case.

Fix patch_set_status checks

---

.github/scripts/parse_false_positive_comment.sh

Sort comments by the patchset they were posted for and pick only those patchsets which are <= $patch_set the workflow was triggered by.

.github/scripts: Change condition for picking up Build failed comments

---

.github/scripts/parse_false_positive_comment.sh
.github/workflows/gerrit-webhook-handler.yml

Do not process events from changes which are either private or belong to branches where anonymous user doesn't have access (e.g. refs/meta/config branches).
If it's not readable by anonymous user - don't run it.

Ignore private changes and comments

---

.github/scripts/outdated_changes.py

1) Don't reset Verified vote on slightly (< 2 weeks) changes
2) Don't comment on outdated change if it was already commented on.

Outdated changes minor fixes

---

.github/workflows/build_qcow2.yml

This was unfortunately missed in the [previous PR](https://github.com/spdk/spdk-ci/pull/79) meant to fix Qcow2 building process. Uploaded artifact names need to be unique in scope of the workflow unless `overwrite` is set to true (which is not the case here).

build_qcow2: make cloudinit report artifact name unique

---

cijoe/configs/qemuhost-with-guest-fedora_40.toml

Netsite no longer hosts mirrors of the Fedora Cloud images.

build_qcow: update the fedora 40 cloud image url

---

.github/workflows/gerrit-webhook-handler.yml

Revert commit 1b01351cc5e1d1f73d600186ff59458e8588d272 once HPE runners are back online.

Re-enable HPE NVMe-oF RDMA tests

---

.github/workflows/spdk-common-tests.yml

All other jobs in this workflow are canceled when any of the fails. Without this, all distro tests take up CI time for a result that will still produce a negative vote.

distro: immediately cancel remaining jobs on failure
